---
spring:
  
  main:
    web-application-type: none
    
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:

        single-grape:
          destination: single.grape.topic
          contentType: application/json
          group: amqp-sink

        multi-grapes:
          destination: multi.grape.topic
          contentType: application/json
          group: amqp-sink

use:
  message:
    listener: true

jackson:
  config:
    enabled: true

---
spring:
  profiles: default

  rabbitmq:
    username: admin
    password: admin

---
spring:
  profiles: kafka
  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          headers: color

